/** Shared demo account — must be a valid email domain for Supabase Auth. */
export const DEMO_ACCOUNT = {
  email: "demo@careeros.app",
  password: "careeros-dev-password",
  fullName: "Alex Chen (Demo)",
} as const;

export const DEMO_PROFILE = {
  province: "NS",
  city: "Halifax",
  status: "pgwp" as const,
  permit_expiry: "2027-06-01",
  language_en: "advanced" as const,
  language_fr: "basic" as const,
  target_titles: ["Software Developer", "Data Analyst", "DevOps Engineer"],
  onboarding_completed: true,
  onboarding_step: 5,
  match_score_threshold: 65,
};

export const DEMO_JOBS = [
  {
    slug: "demo-sw-dev-halifax",
    source: "job_bank",
    external_id: "demo-21232-hfx",
    title: "Software Developer",
    company: "Atlantic Tech Solutions",
    city: "Halifax",
    province: "NS",
    url: "https://www.jobbank.gc.ca/jobsearch/jobposting/demo-21232",
    noc_code: "21232",
    teer_level: 1,
    noc_confidence: 0.92,
    wage_offered: 48,
    wage_median_region: 40,
    bilingual_required: false,
    lmia_flag: false,
    match_score: 78,
    gaps: ["Add one more year of Canadian experience to strengthen PNP points."],
    pathway_flags: {
      ee_eligible: true,
      ee_categories: ["STEM"],
      pnp_streams: ["ns_in_demand"],
      aip_relevant: true,
    },
  },
  {
    slug: "demo-data-analyst-toronto",
    source: "job_bank",
    external_id: "demo-21223-tor",
    title: "Data Analyst",
    company: "Maple Analytics Inc.",
    city: "Toronto",
    province: "ON",
    url: "https://www.jobbank.gc.ca/jobsearch/jobposting/demo-21223",
    noc_code: "21223",
    teer_level: 1,
    noc_confidence: 0.88,
    wage_offered: 42,
    wage_median_region: 38,
    bilingual_required: false,
    lmia_flag: false,
    match_score: 74,
    gaps: ["Highlight SQL and dashboard projects on your resume."],
    pathway_flags: {
      ee_eligible: true,
      ee_categories: ["STEM"],
      pnp_streams: ["oinp_human_capital"],
      aip_relevant: false,
    },
  },
  {
    slug: "demo-devops-calgary",
    source: "job_bank",
    external_id: "demo-21231-yyc",
    title: "DevOps Engineer",
    company: "Prairie Cloud Co.",
    city: "Calgary",
    province: "AB",
    url: "https://www.jobbank.gc.ca/jobsearch/jobposting/demo-21231-devops",
    noc_code: "21231",
    teer_level: 1,
    noc_confidence: 0.85,
    wage_offered: 52,
    wage_median_region: 45,
    bilingual_required: false,
    lmia_flag: false,
    match_score: 71,
    gaps: ["AWS certification would improve match score."],
    pathway_flags: {
      ee_eligible: true,
      ee_categories: ["STEM"],
      pnp_streams: ["aaip_tech"],
      aip_relevant: false,
    },
  },
  {
    slug: "demo-ux-vancouver",
    source: "job_bank",
    external_id: "demo-52120-yvr",
    title: "UX Designer",
    company: "Pacific Digital Studio",
    city: "Vancouver",
    province: "BC",
    url: "https://www.jobbank.gc.ca/jobsearch/jobposting/demo-52120",
    noc_code: "52120",
    teer_level: 2,
    noc_confidence: 0.8,
    wage_offered: 36,
    wage_median_region: 34,
    bilingual_required: false,
    lmia_flag: false,
    match_score: 68,
    gaps: ["Portfolio link recommended for design roles."],
    pathway_flags: {
      ee_eligible: true,
      ee_categories: [],
      pnp_streams: ["bc_pnp_skilled_worker"],
      aip_relevant: false,
    },
  },
  {
    slug: "demo-ba-ottawa",
    source: "job_bank",
    external_id: "demo-11202-yow",
    title: "Business Analyst",
    company: "Capital Policy Group",
    city: "Ottawa",
    province: "ON",
    url: "https://www.jobbank.gc.ca/jobsearch/jobposting/demo-11202",
    noc_code: "11202",
    teer_level: 1,
    noc_confidence: 0.83,
    wage_offered: 40,
    wage_median_region: 39,
    bilingual_required: true,
    lmia_flag: false,
    match_score: 66,
    gaps: ["French intermediate preferred for bilingual Ottawa roles."],
    pathway_flags: {
      ee_eligible: true,
      ee_categories: [],
      pnp_streams: ["oinp_french_speaking"],
      aip_relevant: false,
    },
  },
] as const;

export const DEMO_PATHWAY_REPORT = {
  generated_at: new Date().toISOString(),
  disclaimer:
    "Informational only, based on published program criteria — not immigration advice.",
  profile_summary: {
    status: "pgwp",
    province: "NS",
    permit_expiry: "2027-06-01",
    language_en: "advanced",
    language_fr: "basic",
  },
  canadian_experience: {
    total_months: 14,
    by_noc: { "21232": 14 },
    primary_noc: "21232",
    primary_teer: 1,
  },
  pathway_flags: {
    ee_eligible: true,
    ee_categories: ["STEM"],
    pnp_streams: ["ns_in_demand", "oinp_human_capital"],
    aip_relevant: true,
  },
  ee_teer_eligible: true,
  recommendations: [
    "Target TEER 0–3 NOC 21232 roles in Nova Scotia — strong AIP and NS PNP alignment.",
    "Keep permit expiry in view; prioritize employers open to PGWP-to-PR pathways.",
    "Improve French to intermediate to unlock additional OINP and EE category draws.",
  ],
};

export const DEMO_ACTIVITY = [
  {
    action: "discovery_completed",
    summary: "Found 5 eligible matches after permit and LMIA filters.",
    metadata: { sources: ["job_bank"], matches: 5, filtered: 12 },
  },
  {
    action: "jobs_filtered",
    summary: "Removed 12 jobs requiring LMIA or security clearance you don't hold.",
    metadata: { filtered_count: 12 },
  },
  {
    action: "pathway_report_generated",
    summary: "Pathway report generated for PGWP profile in Nova Scotia.",
    metadata: { ee_eligible: true },
  },
];
